### ISSUE TITLE
out of memory issue

### ISSUE THREAD

**Issue by yujjang** [ACEnglish/utmos#2]
Dear all, 

I have read your SVCollector paper interestingly and have some questions. 

1. In SVCollector github, I can choose the greedy, topN options, But which method is used in Utmos?

2. I'm getting trouble with memory issue..How can I reduce memory usage? My input vcf data is from 'http://ftp.1000genomes.ebi.ac.uk/vol1/ftp/data_collections/1000G_2504_high_coverage/working/20220422_3202_phased_SNV_INDEL_SV/'

When I tested this chr 22 vcf file, utmos is worked well. 
(the code is utmos select -c $count --af -o $file.jl -subset $list.txt ./input)
But I want to select the samples in whole chromosomes, So I used bcftools to concate chr1-22 and used same code but got 'out of memory' issue.😭
Could you recommend a way to solve this problem? 

Thank you !

**Comment by ACEnglish** [comment]
Hello,

1. The Utmos implementation runs the greedy heuristic method. The other two methods were controls to measure the greedy method against and weren't ported over to the rewrite.
2. To get around the memory issue, I would recommend using `utmos convert` on each chromosome independently. This will limit memory usage by converting subsets of the data to the `output.jl` format. During conversion, you can use `--lowmem` and `--buffer` (described in the README) to use less memory. You can then provide all the `output.jl` files to `utmos select` and use `--lowmem`, `--buffer`, `--maxmem` (again described in the README) to use less memory. 

I don't have any recommendations on what values to use with `buffer` or `maxmem` as it depends on the data. But with a little playing around it should be able to work. If you have any problems interpreting these memory-releated parameters, reopen this ticket with questions and I'll be happy t provide more information.

Have a great day,
~/Adam
