### ISSUE TITLE
How can I combine all individual .jl files?

### ISSUE THREAD

**Issue by yujjang** [ACEnglish/utmos#3]
Dear All,

Hi, 
first of all, Thank you for your quick response, which was really helpful to me. 
As your comment, I was able to convert all .vcf files into .jl file.
In the next step, I want to combine all chromosome files to get sample scores using greedy method. 
But, When I added 2 more input files, I got the following error : 

File "/usr/local/bin/utmos", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/utmos/__main__.py", line 47, in main
    TOOLS[args.cmd](args.options)
  File "/usr/local/lib/python3.8/dist-packages/utmos/select.py", line 300, in select_main
    data = load_files(args.in_files, args.lowmem, args.af)
  File "/usr/local/lib/python3.8/dist-packages/utmos/select.py", line 214, in load_files
    elif not samp_same(samples, dat['samples']):
  File "/usr/local/lib/python3.8/dist-packages/utmos/select.py", line 193, in samp_same
    return len(a) == len(b) and np.equal(a, b).all()
numpy.core._exceptions.UFuncTypeError: ufunc 'equal' did not contain a loop with signature matching types (<class 'numpy.dtype[str_]'>, <class 'numpy.dtype[str_]'>) -> None

My input code is : 
utmos select -c 10 --af -o ./1kGP_10.jl --subset ./list1.txt 1kGP.chr22.vcf.jl ./1kGP.chr21.vcf.jl

How can I combine all individual .jl files?  Please give me some advice.

Thanks once again,

Best regards
Yujin

**Comment by ACEnglish** [comment]
Hello,

I've not seen this error before, from this tool or any other. Your command looks to be correct. The code is failing when it checks the list of samples in the two files are identical. That error is telling us that the list in the first file is an array of type `str`, while the other is `numpy.str_`. Those two types are comparable, 
```python
>>> import numpy
>>> numpy.str_
<class 'numpy.str_'>
>>> x = numpy.str_('a')
>>> x
'a'
>>> x == 'a'
True
```

but apparently numpy doesn't have a method to compare across the types... I'm not sure. Regardless, if the two input VCFs were converted identically, then the types should be the same. My suspicion is that they weren't converted identically. Perhaps one with `utmos convert --lowmem` and another without `--lowmem`. 

If this is the case, converting them identically would likely solve the problem. 

Also, if this is the case, I've spotted a line (83 in convert.py) where I can  maybe fix the problem. 

Also, it may be possible that your numpy version should be updated (` python3 -m pip install numpy --upgrade`)? I tried to recreate the issue and didn't have any problems using 'numpy==1.24.4'

**Comment by yujjang** [comment]
Hi,

Thank you for replying! 

I used the utmos v1.0 in dockerhub, I think it is matter to me. 

When I installed utmos v2.2, this error doesn't happend.

But, Sorry, I encountered another problem like below : 

 utmos select -c 10 --af -o /home/mtl/1kgp/utmos/test/test.test.10.jl /home/mtl/1kgp/utmos/1kGP_high_coverage_Illumina.chr22.filtered.SNV_INDEL_SV_phased_panel.jl
2023-10-04 00:18:30,976 [INFO] Params:
{
    "in_files": [
        "/home/mtl/1kgp/utmos/1kGP_high_coverage_Illumina.chr22.filtered.SNV_INDEL_SV_phased_panel.jl"
    ],
    "count": 10.0,
    "out": "/home/mtl/1kgp/utmos/test/test.test.10.jl",
    "debug": false,
    "af": true,
    "weights": null,
    "subset": null,
    "exclude": null,
    "lowmem": null,
    "buffer": 32768,
    "maxmem": 2
}
2023-10-04 00:18:30,977 [INFO] Loading 1 files
Traceback (most recent call last):
  File "/home/mtl/1kgp/alphafold/alphafold/miniconda3/bin/utmos", line 8, in <module>
    sys.exit(main())
  File "/home/mtl/1kgp/alphafold/alphafold/miniconda3/lib/python3.9/site-packages/utmos/__main__.py", line 47, in main
    TOOLS[args.cmd](args.options)
  File "/home/mtl/1kgp/alphafold/alphafold/miniconda3/lib/python3.9/site-packages/utmos/select.py", line 428, in select_main
    data = load_files(args.in_files, args.lowmem, args.buffer, args.af)
  File "/home/mtl/1kgp/alphafold/alphafold/miniconda3/lib/python3.9/site-packages/utmos/select.py", line 280, in load_files
    af_parts.append(dat['AF'][uninf_filter])
TypeError: 'NoneType' object is not subscriptable


Thanks, 
Yujin

**Comment by ACEnglish** [comment]
Okay, that's good to know that the version was just outdated.

For the new error, there was a change in the structure of utmos convert joblib files between v1 and v2. Did you get this error when trying to run utmos_v2 select on utmos_v1 converted data? If so, you'll need to redo that conversion with v2

**Comment by yujjang** [comment]
That was my problem and now, it totally work! Thank you !!
